// <auto-generated />
using System;
using Microservice.Whatevers.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Microservice.Whatevers.Api.Migrations
{
    [DbContext(typeof(WhateverContext))]
    [Migration("20200412044815_First migration")]
    partial class Firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Microservice.Whatevers.Domain.Entities.Things.Thing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Thing");
                });

            modelBuilder.Entity("Microservice.Whatevers.Domain.Entities.Whatevers.Whatever", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Whatever");

                    b.HasData(
                        new
                        {
                            Id = new Guid("32890bb3-92a3-483c-a026-4c9f05d357e5"),
                            Name = "Whatever",
                            Time = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Some type"
                        },
                        new
                        {
                            Id = new Guid("54874289-e551-4c6c-ac96-bba45e201245"),
                            Name = "Whatever",
                            Time = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            Type = "Another type"
                        },
                        new
                        {
                            Id = new Guid("dd0fd502-d6eb-408e-8836-754565946930"),
                            Name = "Whatever",
                            Time = new DateTime(2020, 4, 12, 1, 48, 15, 422, DateTimeKind.Local).AddTicks(2819),
                            Type = "More another type"
                        },
                        new
                        {
                            Id = new Guid("ebfde1d8-2202-4ebe-856a-d8cf7dafcaf3"),
                            Name = "Whatever",
                            Time = new DateTime(2020, 4, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Type = "Once more type"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
